// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Accounts struct {
	ID          int64         `json:"id"`
	Owner       string        `json:"owner"`
	Balance     int64         `json:"balance"`
	Currency    string        `json:"currency"`
	CreatedAt   time.Time     `json:"created_at"`
	CountryCode sql.NullInt32 `json:"country_code"`
}

type Entries struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be positive or negative
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfers struct {
	ID      int64 `json:"id"`
	FromAcc int64 `json:"from_acc"`
	ToAcc   int64 `json:"to_acc"`
	// needs to be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
